version: 2.1
jobs:
    build:
      docker:
      - image: circleci/elixir:1.8.2
      steps:
      - checkout
      - run: mix do deps.get, deps.compile
      - run: mix compile --warnings-as-errors
    format_check:
      docker:
      - image: circleci/elixir:1.8.2
      steps:
      - checkout
      - run: mix format --check-formatted
      - run: mix credo --strict

workflows:
  version: 2.
  build_and_test:
    jobs:
    - build
    - format_check:
        requires:
            - build