version: 2.1
executors:
  minimal-elixir:
    docker:
      - image: hexpm/elixir:1.14.0-erlang-24.3-alpine-3.15.0
        environment:
          DOCKER_ENV: test
          MIX_ENV: test
jobs:
    build:
      executor: minimal-elixir
      steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get
    format_credo_check:
      executor: minimal-elixir
      steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get
      - run: mix deps.compile
      - run: mix format --check-formatted
      - run: mix credo --strict
workflows:
  version: 2.
  build_and_test:
    jobs:
    - build
    - format_credo_check:
        requires:
            - build