name: "Validate PR Title"

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          validateSingleCommit: true
          # Ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title/commit
            "{title}" didn't match the configured pattern. Please ensure that
            the subject doesn't start with an uppercase character.
